### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by jbgi** [comment]
Looks like somehow password login got disabled when I updated nix-mineral. Not sure if this is due to this branch or an earlier commit. Converting to draft until I bisect this.

**Comment by jbgi** [comment]
Fixed the login issue (which was appeared after the last `l.mkDefault` changes which made the nix-mineral pam setting actually effective) in last commit.

**Review by RAVENz46 — APPROVED** [review]
Thanks for your work, I forgot fixing to avoid conflict default settings.
Confirm that works fine!

**Comment by cynicsketch** [comment]
Thanks for the PR! All looks good.

**Pull request merged**
