### PR TITLE
A possible implementation of fetching the Kicksecure configs from upstream

### PR DESCRIPTION
**Pull request by wyyllou**
Relevant: #7 

Have not tested yet

### CODE REVIEW

**Comment by cynicsketch** [comment]
Looks good so far. I'm not an expert nix dev, by any stretch of the imagination. I'll try to do some manual testing later.

**Comment by wyyllou** [comment]
> Looks good so far. I'm not an expert nix dev, by any stretch of the imagination. I'll try to do some manual testing later.

if you have any questions or want me to refine the implementation, feel free to ping me :)

**Comment by wyyllou** [comment]
fyi, i also inadvertently updated the configs to the latest commit of today, which was easier than looking which commit the configs were from. They probably haven't changed anyway, but just thought you might want to know.

**Comment by wyyllou** [comment]
An alternative implementation is pulling the entire kicksecure repository into the file with fetchGithub function(? may be named differently) and referencing from that, but i decided against it since it unnecessarily increases your closure size by the size of the repository, when we are picking out 3 files. That also would not let you pick out the files from different commits of the repository.

**Comment by wyyllou** [comment]
(just merged the formatting changes i made from before)

**Comment by cynicsketch** [comment]
> An alternative implementation is pulling the entire kicksecure repository into the file with fetchGithub function(? may be named differently) and referencing from that, but i decided against it since it unnecessarily increases your closure size by the size of the repository, when we are picking out 3 files. That also would not let you pick out the files from different commits of the repository.

We don't want to do that (for now) when a good chunk of the repository doesn't apply to NixOS. Debian/apt specific hardening, miscellaneous configuration files to unbreak xfce, scripts that don't have anywhere to go, etc.

**Comment by wyyllou** [comment]
> We don't want to do that (for now) when a good chunk of the repository doesn't apply to NixOS. Debian/apt specific hardening, miscellaneous configuration files to unbreak xfce, scripts that don't have anywhere to go, etc.

I did not explicitly mean to apply all files. But the method pulls the repository into the nix store (imagine git cloning the repository into the store) (thus making nix-mineral depend on the kicksecure repository being in the store) then you can reference the store path in nix-mineral.nix. That is the same way the flake method works for using nix-mineral, it pulls this repository into the store, and you reference the path to nix-mineral.nix with "${inputs.nix-mineral}/nix-mineral.nix" which evaluates to a nix store path with this repository in it.

**Comment by cynicsketch** [comment]
> I did not explicitly mean to apply all files. But the method pulls the repository into the nix store (imagine git cloning the repository into the store) (thus making nix-mineral depend on the kicksecure repository being in the store) then you can reference the store path in nix-mineral.nix. That is the same way the flake method works for using nix-mineral (apart from this would not be dependent on flakes. it could be if you wanted it to, though), it pulls this repository into the store, and you reference the path to nix-mineral.nix with "${inputs.nix-mineral}/nix-mineral.nix" which evaluates to the nix store path of this repository that was pulled in by the flake.

That makes more sense to me now.

On further observation, I don't think closure size would be a big problem for 99% of people, since the whole repository takes only 5.2mb and NixOS is already way too chunky by design to be penny pinching at that those sizes.

Then it becomes the question of weighing against how much we trust Kicksecure to submit reasonably stable commits vs. not trusting them and picking the individual commits manually. 

Given the current implementation of nix-mineral (manually defining sysctl, boot parameters, etc) I think using fetchGhFile makes the most sense at the moment. There's no point to completely anchoring to another repository on a few things when manual maintenance would still be needed on our end anyways.

**Comment by wyyllou** [comment]
The only downside of this method is the upl dating commits and hashes, but its kinda a non-issue because i don't think its too hard to update the commits once in a while - i could probably make a github action to automate it too by checking if the file changes (probably manual trigger so you can audit the new code)

**Comment by cynicsketch** [comment]
> The only downside of this method is the updating commits and hashes, but its kinda a non-issue because i don't think its too hard to update the commits once in a while - i could probably make a github action to automate it too by checking if the file changes (probably manual trigger so you can audit the new code)

Great idea! I'm all for it if it makes maintenance easier.

**Pull request closed without merging**
