### PR TITLE
Refactoring and formatting

### PR DESCRIPTION
**Pull request by wyyllou**
Remove "with lib;" and use a more sensible method (l)
added l = lib // builtins; (a common nix pattern) to replace it
since using "with" on such a big scope is discoraged.

Referencing lix.systems:
Prefer not to use with to bring things into scope as it obscures the source of variables and degrades language server diagnostics.

did some additional formatting that i missed out in the previous PR

This probably needs testing since it is code will change the evaluation.

### CODE REVIEW

**Comment by cynicsketch** [comment]
> This probably needs testing since it is code will change the evaluation.

Just reviewed the code and tested it. It's mostly good with the exception of one line, which was easy to modify and get to evaluate properly.

Original:
`systemd.network.config.networkConfig.IPv6PrivacyExtensions = l.mkDefault kernel;`

Fixed (missing quotation marks):
`systemd.network.config.networkConfig.IPv6PrivacyExtensions = l.mkDefault "kernel";`

**Comment by wyyllou** [comment]
> > This probably needs testing since it is code will change the evaluation.
> 
> Just reviewed the code and tested it. It's mostly good with the exception of one line, which was easy to modify and get to evaluate properly.
> 
> Original: `systemd.network.config.networkConfig.IPv6PrivacyExtensions = l.mkDefault kernel;`
> 
> Fixed (missing quotation marks): `systemd.network.config.networkConfig.IPv6PrivacyExtensions = l.mkDefault "kernel";`

Yep, i forgot to mention that. Actually, a consequence of using the with lib; before was that, that issue wasn't picked up by my LSP (^^degrades language server diagnostics.)

**Comment by wyyllou** [comment]
Should be ready to merge now :3

**Comment by cynicsketch** [comment]
Works good, no apparent feature loss after review, so I'm merging.

**Pull request merged**
